# Generated by Django 2.1.7 on 2019-03-25 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='End',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_now', models.DateTimeField(default=datetime.datetime.now)),
                ('date_exit', models.DateTimeField(default=datetime.datetime(2019, 3, 29, 11, 0))),
            ],
        ),
    ]
