# Generated by Django 2.1.7 on 2019-03-25 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urentot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end',
            name='date_now',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 16, 7, 57, 478923)),
        ),
    ]
