# Generated by Django 2.1.7 on 2019-03-25 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urentot', '0002_auto_20190325_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end',
            name='date_now',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 16, 36, 17, 773604)),
        ),
    ]
